name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build --pull --no-cache -t darkcheyenne/docker-rolling-updated:latest -t docker.pkg.github.com/darkcheyenne/ubuntu-rolling-updated/base:latest .
    - name: Upload Image
      run: docker push docker.pkg.github.com/darkcheyenne/ubuntu-rolling-updated/base:latest
